<a href="https://colab.research.google.com/github/sangjunlim-dev/ml-practicals/blob/main/numpy_essentials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import numpy as np

### Creating Arrays

In [ ]:
arr0 = np.array([1, 2, 3])

arr1 = np.zeros(3)

arr2 = np.ones(3)

# Initial content is random (depends on state of the memeory)
arr3 = np.empty(3)

arr4 = np.arange(4)

# Array with values spaced linearly
arr5 = np.linspace(0, 10, num=5)

### Arthmetic and Sorting

In [ ]:
arr6 = np.array([2, 1, 4, 3, 7, 5, 6])

# Ascending Sort
np.sort(arr6)

# Descending sort
np.sort(arr6)[::-1]

array([7, 6, 5, 4, 3, 2, 1])

In [ ]:
arr7 = np.random.randint(0, 10, 12).reshape([3, 4])
arr7

array([[5, 5, 1, 7],
       [6, 3, 8, 6],
       [5, 6, 0, 2]])

In [ ]:
# Sort by column
np.sort(arr7)[:, ::-1]

array([[7, 5, 5, 1],
       [8, 6, 6, 3],
       [6, 5, 2, 0]])

In [ ]:
# Sort by row
np.sort(arr7, axis=0)

array([[5, 3, 0, 2],
       [5, 5, 1, 6],
       [6, 6, 8, 7]])

In [ ]:
# Return index after sorted
np.argsort(arr7)

array([[2, 0, 1, 3],
       [1, 0, 3, 2],
       [2, 3, 0, 1]])

In [ ]:
a = np.array([[1, 2],
               [3, 4]])
b = np.array([[5, 6]])

np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

### Dimension, Size and Exapnd

In [3]:
a8 = np.arange(6)
a8

array([0, 1, 2, 3, 4, 5])

In [8]:
a8.ndim, a8.size, a8.shape

(1, 6, (6,))

In [9]:
a8.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

####Use `np.newaxis` and `np.expand_dims` to increase the dimension.

In [13]:
# Convert 1D array to a vector
a9 = a8[np.newaxis, :]

a8.shape, a9.shape

((6,), (1, 6))

In [14]:
# Add an axis at index position 0
a10 = np.expand_dims(a8, axis=0)

a10.shape

(1, 6)

### Indexing and Slicing

In [21]:
a11 = np.arange(12)
a11 = a11.reshape(3, 4)
a11

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

####Use condition on array to get boolean array.

In [24]:
a11 < 5

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

####Use condition as an index to get all the values meeting the condition.

In [23]:
a11[a11 < 5]

array([0, 1, 2, 3, 4, 5])

#### If you apply condition within `np.nonzero` tuple of arrays will be returned.


In [31]:
#First array represent row indicies, Second array represent column indicies
np.nonzero(a11)

(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]),
 array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))